version: '3.8'
services:
  db:
    image: mysql:8
    ports:
      - "3305:3306"
    environment:
      - MYSQL_DATABASE='accesos_wifi'
      - MYSQL_USER='arkon_test'
      - MYSQL_PASSWORD='arkon_test'
      - MYSQL_ROOT_PASSWORD='arkon_test'
      #- MYSQL_HOST='127.0.0.1'
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/arkon_api
      - /tmp/app/mysqld:/run/mysqld
    container_name: django_graphql_api
    depends_on:
      - db
