# Generated by Django 4.1.5 on 2023-01-14 02:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_wifi', models.CharField(error_messages={'blank': 'No puede estar vacío.', 'required': 'No puede estar vacío.'}, max_length=1000, validators=[django.core.validators.MinLengthValidator(0, message='La descripción debe tener por lo menos 1 caracter.'), django.core.validators.MaxLengthValidator(1000, message='No puede pasar los 1000 caracteres.')], verbose_name='Identificador:')),
                ('programa', models.CharField(error_messages={'blank': 'No puede estar vacío.', 'required': 'No puede estar vacío.'}, max_length=1000, validators=[django.core.validators.MinLengthValidator(1, message='El programa debe tener por lo menos 1 caracter.'), django.core.validators.MaxLengthValidator(1000, message='No puede pasar los 1000 caracteres.')], verbose_name='Programa:')),
                ('fecha_instalacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de instalación')),
                ('latitud', models.DecimalField(decimal_places=6, default=0, error_messages={'invalid': 'El valor debe ser numérico.', 'max_decimal_places': 'No puedes ingresar más de 6 decimales.', 'max_digits': 'No puedes ingresar más de 8 dígitos en total.', 'max_whole_digits': 'No puedes tener mas de 8 enteros.'}, max_digits=8, verbose_name='Latitud:')),
                ('longitud', models.DecimalField(decimal_places=6, default=0, error_messages={'invalid': 'El valor debe ser numérico.', 'max_decimal_places': 'No puedes ingresar más de 6 decimales.', 'max_digits': 'No puedes ingresar más de 8 dígitos en total.', 'max_whole_digits': 'No puedes tener mas de 8 enteros.'}, max_digits=9, verbose_name='Longitud:')),
                ('colonia', models.CharField(error_messages={'blank': 'No puede estar vacío.', 'required': 'No puede estar vacío.'}, max_length=1000, validators=[django.core.validators.MinLengthValidator(1, message='La colonia debe tener por lo menos 1 caracter.'), django.core.validators.MaxLengthValidator(1000, message='No puede pasar los 1000 caracteres.')], verbose_name='Colonia:')),
                ('alcaldia', models.CharField(error_messages={'blank': 'No puede estar vacío.', 'required': 'No puede estar vacío.'}, max_length=1000, validators=[django.core.validators.MinLengthValidator(1, message='La alcaldía debe tener por lo menos 1 caracter.'), django.core.validators.MaxLengthValidator(1000, message='No puede pasar los 1000 caracteres.')], verbose_name='Alcaldía:')),
            ],
        ),
    ]
