# Generated by Django 4.1.5 on 2023-01-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifipoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesos',
            name='latitud',
            field=models.DecimalField(decimal_places=8, default=0, error_messages={'invalid': 'El valor debe ser numérico.', 'max_decimal_places': 'No puedes ingresar más de 6 decimales.', 'max_digits': 'No puedes ingresar más de 8 dígitos en total.', 'max_whole_digits': 'No puedes tener mas de 8 enteros.'}, max_digits=10, verbose_name='Latitud:'),
        ),
        migrations.AlterField(
            model_name='accesos',
            name='longitud',
            field=models.DecimalField(decimal_places=8, default=0, error_messages={'invalid': 'El valor debe ser numérico.', 'max_decimal_places': 'No puedes ingresar más de 6 decimales.', 'max_digits': 'No puedes ingresar más de 8 dígitos en total.', 'max_whole_digits': 'No puedes tener mas de 8 enteros.'}, max_digits=10, verbose_name='Longitud:'),
        ),
    ]
